### ISSUE TITLE
Do not save config if no changes were made while modifying it in ASF-ui

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1417]
## Purpose
Do not save (re-save) bot's config file, which will force ASF to reconnect the bot, if there are no changes in config.

If user opens bot's config panel from bot's card in ASF-ui and presses Save button, but didn't make any config changes, even if he switched any setting to false and then back to true for example, ASF-ui doesn't need to save the config file in this case, as no changes were made in fact.

**Comment by Botan626** [comment]
The issue is also valid for ASF Config and UI Config pages.

**Comment by MrBurrBurr** [comment]
> This issue also applies to ASF Config, UI Config and Mass Editor pages.

With latest commit ASF Config and Bot Config will not save identical config. Mass Editor already checks for identical bot config.

No need for UI Config to check IMHO.

**Comment by JustArchi** [comment]
> No need for UI Config to check IMHO.

It makes sense to optimize amount of requests to the backend, in this case to ASF. If UI config isn't sent anywhere but saved locally, it doesn't make sense for a pre-check because checking if it's the same might be sometimes even more work than just saving it outright, so that's up to ASF-ui discretion. It's totally worthy to optimize requests to other services though.

**Comment by MrBurrBurr** [comment]
We save UI Config in local storage and are not sending any requests to ASF, so no need to check since it might even take longer to first check what's in localStorage than to just overwrite it.

**Comment by Botan626** [comment]
> With latest commit ASF Config and Bot Config will not save identical config. Mass Editor already checks for identical bot config.

I can confirm this for Mass Editor, but not for ASF Config and Bot Config, configs would be re-saved when pressing Save button, ASF would restart and bots would reconnect.

**Comment by MrBurrBurr** [comment]
> I can confirm this for Mass Editor, but not for ASF Config and Bot Config

Not sure I understand what you mean. Are you saying that, even with latest commit, ASF Config and Bot Config are still not checking for identical old config?

**Comment by Botan626** [comment]
> Not sure I understand what you mean. Are you saying that, even with latest commit, ASF Config and Bot Config are still not checking for identical old config?

That is exactly my point.

**Comment by Botan626** [comment]
https://i.imgur.com/zHPS2LX.gif

**Comment by MrBurrBurr** [comment]
> That is exactly my point. Do you want to see a gif?
No, thank you for reporting it. I found the bug. Will fix it later.

**Comment by MrBurrBurr** [comment]
@Botan626 Should work now. Feel free to verify. If it doesn't work, please provide an example ASF.json config file so I can reproduce.

**Comment by Botan626** [comment]
> @Botan626 Should work now. Feel free to verify. If it doesn't work, please provide an example ASF.json config file so I can reproduce.

Still doesn't work as wanted. I only checked ASF config this time.
```
{
  "Blacklist": [
    362890
  ],
  "ConfirmationsLimiterDelay": 15,
  "CurrentCulture": "en-US",
  "FarmingDelay": 10,
  "GiftsLimiterDelay": 3,
  "Headless": true,
  "IdleFarmingPeriod": 4,
  "InventoryLimiterDelay": 15,
  "LoginLimiterDelay": 15,
  "Statistics": false,
  "SteamOwnerID": 76561197960895331,
  "UpdateChannel": 2,
  "UpdatePeriod": 0
}

**Comment by MrBurrBurr** [comment]
Thank you. Let's try one final time: It should be fixed now.

**Comment by Botan626** [comment]
Its's half fixed. If I choose any config property, make it false and then true back again, ASF will restart, if I press Save button.

Bots will reconnect if I just press Save button.

**Comment by MrBurrBurr** [comment]
It should be fixed now.™

**Comment by Botan626** [comment]
> It should be fixed now.™

Not for bots configs.

**Comment by MrBurrBurr** [comment]
Please provide a example config so I can reproduce it.

**Comment by Botan626** [comment]
> Please provide a example config so I can reproduce it.

```
{
  "AcceptGifts": true,
  "AutoSteamSaleEvent": true,
  "BotBehaviour": 7,
  "Enabled": true,
  "FarmingOrders": [
    3
  ],
  "GamesPlayedWhileIdle": [
    515040
  ],
  "HoursUntilCardDrops": 1,
  "LootableTypes": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "MatchableTypes": [],
  "SendTradePeriod": 1,
  "SteamLogin": "*****",
  "SteamPassword": "*****",
  "SteamUserPermissions": {
    "76561197960895331": 3
  },
  "TradingPreferences": 1
}

**Comment by Botan626** [comment]
Also Mass Editor could show different notification, when not saving config.

`Config property (properties) already of the same value (values) for selected bot (bots)!` suits perfectly in my opinion, this way the user will know he didn't choose new values for selected config properties to save.

**Comment by MrBurrBurr** [comment]
Thank you for the example config. I was able to reproduce it and fix the bug. 🎉 

Feel free to verify.

**Comment by Botan626** [comment]
> Thank you for the example config. I was able to reproduce it and fix the bug. 🎉
> 
> Feel free to verify.

Looks like it's fixed now.


> Also Mass Editor could show different notification, when not saving config.
> 
> `Config property (properties) is (are) already of the same value (values) for selected bot (bots)!` suits perfectly in my opinion, this way the user will know he didn't choose new values for selected config properties to save.

Why you didn't notice this comment?
